#!/usr/bin/env bash
# Backup and restore the homerc and config files quickly
# Bin Li <binli@ubuntu.com>

usage()
{
    echo "Usage: $0 backup|rconfig|pkgs|dconf|chrome|firefox"
    echo "  backup   - Backup homerc and config files, installed package list, and gnome dconf settings"
    echo "  rconfig  - Restore homerc and config files from backup"
    echo "  pkgs     - Restore installed packages from backup"
    echo "  dconf    - Restore gnome dconf settings from backup"
    echo "  chrome   - Install google-chrome browser"
    echo "  firefox  - Install latest firefox browser(non-snap), snap version will be removed"
}

RC_FILELIST="bashrc vim vimrc tmux.conf zshrc gitconfig inputrc profile gnupg ssh"
CONFIG_FILELIST="jenkins_job rclone oem-scripts"

BACKUP=$1
BD="backup-$(whoami)"
if [ -z "$BACKUP" ]; then
    usage
    exit 1
else
    mkdir -p "$BD"
fi

dump_gnome_dconf()
{
    # Dump gnome dconf settings to a file
    dconf dump / > "$BD"/dconf-settings.txt
    echo -e "\e[32mOK\e[0m"
    echo -e "\e[31mNOTE:\e[0m Please review the $BD/dconf-settings.txt and remove any unwanted settings before restoring.\n"
}

save_package_list()
{
    # From /etc/os-release, determine the package manager and get the installed package list
    if [ -f /etc/os-release ]; then
        # shellcheck disable=SC1091
        source /etc/os-release
        case $ID in
            ubuntu|debian)
                dpkg --get-selections | awk '{print $1}' > "$BD"/ubuntu_pkg.list
                echo -e "\e[32mOK\e[0m"
                echo -e "\e[31mNOTE:\e[0m Please review the $BD/package-list.txt and remove any unwanted packages before restoring.\n"
                ;;
            fedora|centos|rhel)
                rpm -qa > "$BD"/package-list.txt
                ;;
            arch)
                pacman -Qqe > "$BD"/package-list.txt
                ;;
            *)
                echo "Unsupported OS for package list backup."
                ;;
        esac
    else
        echo "/etc/os-release not found. Cannot determine OS."
    fi
}

backup_rconfig()
{
    # Make the backup dir with the current username
    mkdir -p "$BD"/config
    mkdir -p "$BD"/homerc
    for rcfile in $RC_FILELIST
    do
        dotrc=$HOME/.$rcfile
        if [ -e "$dotrc" ]; then
            echo -e "Backing up $dotrc..."
            cp -r "$dotrc" "$BD/homerc/$rcfile"
            echo -e "\e[32mOK\e[0m"
        fi
    done
    for conffile in $CONFIG_FILELIST
    do
        homeconf=$HOME/.config/$conffile
        if [ -e "$homeconf" ]; then
            echo -e "Backing up $homeconf..."
            cp -r "$homeconf" "$BD"/config/
            echo -e "\e[32mOK\e[0m"
        fi
    done
}

restore_rconfig()
{
    RCDIR=$PWD/"$BD"/homerc
    CONFDIR=$PWD/"$BD"/config

    if [ ! -d "$BD"  ]; then
        echo "Backup directory $BD does not exist. Cannot restore."
        exit 1
    fi

    if [ -d "$RCDIR" ]; then
        RC_LIST=$(ls "$RCDIR")
    fi
    if [ -d "$CONFDIR" ]; then
        CONFIG_LIST=$(ls "$CONFDIR")
    fi

    for rcfile in $RC_LIST
    do
        dotrc=$HOME/.$rcfile
        echo -e "Restoring $dotrc..."
        if [ -e "$dotrc" ] && [ ! -L "$dotrc"  ]; then
            echo -e "Backing up existing $dotrc to $dotrc.bak"
            mv "$dotrc" "$dotrc".bak
        fi
        echo -e "Creating symlink for $dotrc..."
        ln -sf "$RCDIR"/"$rcfile" "$dotrc"
    done

    for conffile in $CONFIG_LIST
    do
        homeconf="$HOME/.config/$conffile"
        if [ -d "$homeconf" ] && [ ! -L "$homeconf" ]; then
            echo -e "Backing up existing $homeconf to $homeconf.bak"
            mv "$homeconf" "$homeconf".bak
        fi
        echo -e "Creating symlink for $homeconf..."
        ln -sf "$PWD/$BD/config/$conffile" "$homeconf"
    done
}

restore_packages()
{
    if [ ! -f "$BD"/package-list.txt ]; then
        echo "Package list file not found in backup directory."
        exit 1
    fi

    if [ -f /etc/os-release ]; then
        # shellcheck disable=SC1091
        . /etc/os-release
        case $ID in
            ubuntu|debian)
                xargs -a "$BD"/ubuntu_pkg.list sudo apt-get install -y
                ;;
            fedora|centos|rhel)
                xargs -a "$BD"/package-list.txt sudo dnf install -y
                ;;
            arch)
                xargs -a "$BD"/package-list.txt sudo pacman -S --noconfirm
                ;;
            *)
                echo "Unsupported OS for package restoration."
                ;;
        esac
    else
        echo "/etc/os-release not found. Cannot determine OS."
    fi
}

restore_dconf()
{
    if [ ! -f "$BD"/dconf-settings.txt ]; then
        echo "Dconf settings file not found in backup directory."
        exit 1
    fi
    dconf load / < "$BD"/dconf-settings.txt
}

init_firefox()
{
    if [ ! -e /etc/apt/preferences.d/99mozillateam ]; then
        sudo add-apt-repository ppa:mozillateam/ppa -y
        cat > 99mozillateam << EOF
Package: *
Pin: release o=LP-PPA-mozillateam
Pin-Priority: 900
EOF
        sudo mv 99mozillateam /etc/apt/preferences.d/
        sudo apt install firefox -y
    fi
    # Remove the snap version of firefox if it exists
    sudo umount /var/snap/firefox/common/host-hunspell
    snap remove firefox --purge
}

init_chrome()
{
    if [ ! -e /etc/apt/sources.list.d/google-chrome.list ]; then
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv  78BD65473CB3BD13
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /tmp/google-chrome.list
        sudo mv /tmp/google-chrome.list /etc/apt/sources.list.d/
        sudo apt update
        sudo apt install -y google-chrome-stable
    fi
}

if [ "$BACKUP" = "backup" ]; then
    echo "Start backing up rc and config files..."
    backup_rconfig
    echo "Start backing up installed package list..."
    save_package_list
    echo "Start backing up gnome dconf settings..."
    dump_gnome_dconf
    echo -e "Backup completed. Backup directory: \e[33m$BD\e[0m\n"
elif [ "$BACKUP" = "pkgs" ]; then
    echo "Start restoring installed package list..."
    restore_packages
elif [ "$BACKUP" = "dconf" ]; then
    echo "Start restoring gnome dconf settings..."
    restore_dconf
elif [ "$BACKUP" = "rconfig" ]; then
    echo "Start restoring rc and config files..."
    restore_rconfig
elif [ "$BACKUP" = "chrome" ]; then
    echo "Start installing google-chrome..."
    init_chrome
elif [ "$BACKUP" = "firefox" ]; then
    echo "Start installing firefox(non-snap)..."
    init_chrome
else
    usage
    exit 1
fi

