#!/bin/bash
# Restore the rc and config files quickly

RCDIR=$PWD/homerc
CONFDIR=$PWD/config
UPDATE_FLAG=0

i=1 # the resource number

if [ -d $RCDIR ]; then
    RC_LIST=`ls $RCDIR`
fi
if [ -d $CONFDIR ]; then
    CONFIG_LIST=`ls $CONFDIR`
fi

for rcfile in $RC_LIST
do
    dotrc=$HOME/.$rcfile
    echo -e "$i) Try to restore the $dotrc..."
    if [ -e $dotrc -a ! -L $dotrc ]; then
        echo -e "remove $dotrc"
        mv $dotrc $dotrc.bak
    fi
    if [ ! -e $dotrc ]; then
        echo -e "Create $dotrc link now..."
        ln -s $RCDIR/$rcfile $dotrc
        if [ -e $dotrc.bak ]; then
            diff -Naur $dotrc.bak $dotrc
        fi
    else
        echo -e "Skip $dotrc settting."
    fi
    let "i+=1"
done

for conffile in $CONFIG_LIST
do
    homeconf=$HOME/.config/$conffile
    if [ -d $homeconf -a ! -L $homeconf ]; then
        rm -rf $homeconf
    fi
    if [ ! -d $homeconf ]; then
        echo -e "remove $homeconf"
        ln -s $PWD/config/$conffile $homeconf
        echo -e "Link the $conffile at ~/.config/ ..."
    fi
done
init_packages()
{
    package=""
    if [ "$1" = "purge" ]; then
        UBUNTU=`cat ubuntu_pkg.list | grep '^#' | cut -d'#' -f2`
    elif [ "$1" = "install" ]; then
        UBUNTU=`cat ubuntu_pkg.list | grep -v '^#'`
    else
        return
    fi
    for p in $UBUNTU
    do
        package="$package $p"
    done
    echo $package
    if [ "x$package" != "x" ] ; then
        if [ $UPDATE_FLAG -eq 0 ]; then
            sudo apt-get update
            UPDATE_FLAG=1
        fi
        sudo apt-get $1 -y $package
    fi
}

init_firefox()
{
    if [ ! -e /etc/apt/preferences.d/99mozillateam ]; then
        sudo add-apt-repository ppa:mozillateam/ppa -y
        cat > 99mozillateam << EOF
Package: *
Pin: release o=LP-PPA-mozillateam
Pin-Priority: 900
EOF
        sudo mv 99mozillateam /etc/apt/preferences.d/
        sudo apt install firefox -y
    fi
}

init_chrome()
{
    if [ ! -e /etc/apt/sources.list.d/google-chrome.list ]; then
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv  78BD65473CB3BD13
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /tmp/google-chrome.list
        sudo mv /tmp/google-chrome.list /etc/apt/sources.list.d/
        sudo apt update
        sudo apt install -y google-chrome-stable
    fi
}

init_vim()
{
    VIM_PLUGIN=$HOME/.vim/plugin
    if [ ! -e $VIM_PLUGIN ]; then
        mkdir -p $VIM_PLUGIN
    fi
    if [ ! -e $VIM_PLUGIN/dirdiff.vim ]; then
        git clone git@github.com:will133/vim-dirdiff.git
        cp vim-dirdiff/plugin/dirdiff.vim $VIM_PLUGIN/
        rm -rf vim-dirdiff
    fi
    if [ ! -e $VIM_PLUGIN/cscope_macros.vim ]; then
        wget http://www.vim.org/scripts/download_script.php?src_id=171 -O $VIM_PLUGIN/cscope_macros.vim
    fi
    if [ ! -e $VIM_PLUGIN/surround.vim ]; then
        git clone git@github.com:tpope/vim-surround.git
        cp vim-surround/plugin/surround.vim $VIM_PLUGIN/
        rm -rf vim-surround
    fi
    if [ ! -e $VIM_PLUGIN/auto-pairs.vim ]; then
        git clone git@github.com:jiangmiao/auto-pairs.git
        cp auto-pairs/plugin/auto-pairs.vim $VIM_PLUGIN/
        rm -rf auto-pairs
    fi
    if [ ! -e $HOME/.vim/pack/github/start/copilot.vim ]; then
        git clone https://github.com/github/copilot.vim $HOME/.vim/pack/github/start/copilot.vim
    fi
}

init_gnome()
{
    gsettings set org.gnome.desktop.interface enable-hot-corners true
    gsettings set org.gnome.desktop.interface clock-show-weekday true
    gsettings set org.gnome.desktop.interface color-scheme prefer-dark
    gsettings set org.gnome.desktop.interface show-battery-percentage true
    gsettings set org.gnome.desktop.calendar show-weekdate true
    # Screen Blank
    gsettings set org.gnome.desktop.session idle-delay 0
    gsettings set org.gnome.settings-daemon.plugins.media-keys terminal "['<Super>Return']"
    # switch worksapces
    gsettings set org.gnome.shell.keybindings switch-to-application-1 []
    gsettings set org.gnome.shell.keybindings switch-to-application-2 []
    gsettings set org.gnome.shell.keybindings switch-to-application-3 []
    gsettings set org.gnome.shell.keybindings switch-to-application-4 []

    gsettings set org.gnome.desktop.privacy remember-recent-files false

    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-1 "['<Super>1']"
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-2 "['<Super>2']"
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-3 "['<Super>3']"
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-4 "['<Super>4']"
    gsettings set org.gnome.desktop.wm.keybindings unmaximize "['<Super>Down']"
    gsettings set org.gnome.desktop.wm.keybindings maximize "['<Super>Up']"
    gsettings set org.gnome.desktop.wm.keybindings show-desktop "[]"
    # Network Proxy
    gsettings set org.gnome.system.proxy.socks host "127.0.0.1"
    gsettings set org.gnome.system.proxy.socks port 1081

    gsettings set org.gnome.mutter edge-tiling true
    gsettings set org.gnome.mutter.keybindings toggle-tiled-left "['<Super>Left']"
    gsettings set org.gnome.mutter.keybindings toggle-tiled-right "['<Super>Right']"

    gsettings set org.gnome.settings-daemon.plugins.power idle-dim true

}

stop_aptupdate()
{
    sudo systemctl disable apt-daily.timer
    sudo systemctl disable apt-daily-upgrade.timer
    sudo systemctl disable unattended-upgrades.service
}

init_neovim()
{
    #if [ ! -e /usr/bin/nvim ]; then
    #    curl -O https://github.com/neovim/neovim/releases/download/stable/nvim.appimage
    #    chmod u+x nvim.appimage
    #    sudo mv nvim.appimage /usr/bin/nvim
    #    sudo update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 50
    #fi

    packer="$HOME/.local/share/nvim/site/pack/packer/start/packer.nvim"
    if [ ! -e $packer ] ; then
        git clone --depth 1 https://github.com/wbthomason/packer.nvim\
        ~/.local/share/nvim/site/pack/packer/start/packer.nvim
        echo "Clone packer.nvim for neovim"
    fi

    copilot="$HOME/.config/nvim/pack/github/start/copilot.vim"
    if [ ! -e $copilot ]; then
        git clone https://github.com/github/copilot.vim.git \
        ~/.config/nvim/pack/github/start/copilot.vim
        echo "Clone copilot.nvim for neovim"
    fi
}

init_etc()
{
    if [ ! -e /etc/sudoers.d/nopwd ]; then
        sudo cp etc/nopwd /etc/sudoers.d/
    fi
}

sudo umount /var/snap/firefox/common/host-hunspell

init_packages purge
init_packages install
init_vim
init_chrome
init_gnome
stop_aptupdate
#init_neovim
#init_firefox
init_etc

if [ ! -e $HOME/.xinputrc ]; then
    im-config
fi

# Disable BT by default
sudo sed -i "s%AutoEnable=true%AutoEnable=false%" /etc/bluetooth/main.conf
